source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PopupCollectionViewController_Example', :exclusive => true do
  pod 'PopupCollectionViewController', :path => '../'
end

target 'PopupCollectionViewController_Tests', :exclusive => true do
  pod 'PopupCollectionViewController', :path => '../'

  
end
